name: totalexam
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #firebase  
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  #bottombar
  persistent_bottom_nav_bar_v2: ^5.3.0
  board_datetime_picker: ^2.0.0
  curved_navigation_bar: ^1.0.6
  table_calendar: ^3.1.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  lottie: ^3.1.2
  hexcolor: ^3.0.1
  day_night_switcher: ^0.2.0+1
  get_storage: ^2.1.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.6
  sqflite: ^2.3.3+1
  # google 지도 기능
  google_maps_flutter: ^2.7.0
  location: ^7.0.0
  flutter_polyline_points: ^2.1.0
  #floatingbutton
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.7.0 #아이콘
  #game
  like_button: ^2.0.5
  confetti: ^0.7.0
  #상태메세지
  provider: ^6.1.2
  #chart
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_charts: ^26.2.4
  material_segmented_control: ^5.0.1
  fdottedline_nullsafety: ^2.0.1
  flutter_neumorphic: ^3.2.0
  getwidget: ^4.0.0
  percent_indicator: ^4.2.3
  flutter_lints: ^3.0.0
  #chatbot
  flutter_gemini: ^2.0.4
  dash_chat_2: ^0.0.21
  #SNS LOGIN
  google_sign_in: ^6.2.1
  flutter_naver_login: ^1.8.0
  url_launcher: ^6.3.0
  uni_links: ^0.5.1
  #music play
  rxdart: ^0.28.0
  just_audio: ^0.9.39
  #launcher icons
  flutter_launcher_icons: ^0.13.1


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appstore.png"
  min_sdk_android: 21
  
  
  


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/부비.png
    - assets/images/
    - assets/images/mountain.png
    - assets/images2/
    - assets/instar/
    - assets/music/
    - assets/login/
    - assets/animations/foot.json
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #이거시찐이다  
